// Code generated by protoc-gen-go. DO NOT EDIT.
// source: agent.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Agent struct {
	// Output only. SPIFFE ID of the agent.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Output only. The method by which the agent attested.
	AttestationType string `protobuf:"bytes,2,opt,name=attestation_type,json=attestationType,proto3" json:"attestation_type,omitempty"`
	// Output only. The X509-SVID serial number.
	X509SvidSerialNumber string `protobuf:"bytes,3,opt,name=x509svid_serial_number,json=x509svidSerialNumber,proto3" json:"x509svid_serial_number,omitempty"`
	// Output only. The X509-SVID expiration (seconds since Unix epoch).
	X509SvidExpiresAt int64 `protobuf:"varint,4,opt,name=x509svid_expires_at,json=x509svidExpiresAt,proto3" json:"x509svid_expires_at,omitempty"`
	// Output only. The selectors attributed to the agent during attestation.
	Selectors []*Selector `protobuf:"bytes,5,rep,name=selectors,proto3" json:"selectors,omitempty"`
	// Output only. Whether or not the agent is banned.
	Banned               bool     `protobuf:"varint,6,opt,name=banned,proto3" json:"banned,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Agent) Reset()         { *m = Agent{} }
func (m *Agent) String() string { return proto.CompactTextString(m) }
func (*Agent) ProtoMessage()    {}
func (*Agent) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{0}
}

func (m *Agent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Agent.Unmarshal(m, b)
}
func (m *Agent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Agent.Marshal(b, m, deterministic)
}
func (m *Agent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Agent.Merge(m, src)
}
func (m *Agent) XXX_Size() int {
	return xxx_messageInfo_Agent.Size(m)
}
func (m *Agent) XXX_DiscardUnknown() {
	xxx_messageInfo_Agent.DiscardUnknown(m)
}

var xxx_messageInfo_Agent proto.InternalMessageInfo

func (m *Agent) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Agent) GetAttestationType() string {
	if m != nil {
		return m.AttestationType
	}
	return ""
}

func (m *Agent) GetX509SvidSerialNumber() string {
	if m != nil {
		return m.X509SvidSerialNumber
	}
	return ""
}

func (m *Agent) GetX509SvidExpiresAt() int64 {
	if m != nil {
		return m.X509SvidExpiresAt
	}
	return 0
}

func (m *Agent) GetSelectors() []*Selector {
	if m != nil {
		return m.Selectors
	}
	return nil
}

func (m *Agent) GetBanned() bool {
	if m != nil {
		return m.Banned
	}
	return false
}

type AgentMask struct {
	Id                   bool     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AttestationType      bool     `protobuf:"varint,2,opt,name=attestation_type,json=attestationType,proto3" json:"attestation_type,omitempty"`
	X509SvidSerialNumber bool     `protobuf:"varint,3,opt,name=x509svid_serial_number,json=x509svidSerialNumber,proto3" json:"x509svid_serial_number,omitempty"`
	X509SvidExpiresAt    bool     `protobuf:"varint,4,opt,name=x509svid_expires_at,json=x509svidExpiresAt,proto3" json:"x509svid_expires_at,omitempty"`
	Selectors            bool     `protobuf:"varint,5,opt,name=selectors,proto3" json:"selectors,omitempty"`
	Banned               bool     `protobuf:"varint,6,opt,name=banned,proto3" json:"banned,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgentMask) Reset()         { *m = AgentMask{} }
func (m *AgentMask) String() string { return proto.CompactTextString(m) }
func (*AgentMask) ProtoMessage()    {}
func (*AgentMask) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{1}
}

func (m *AgentMask) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentMask.Unmarshal(m, b)
}
func (m *AgentMask) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentMask.Marshal(b, m, deterministic)
}
func (m *AgentMask) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentMask.Merge(m, src)
}
func (m *AgentMask) XXX_Size() int {
	return xxx_messageInfo_AgentMask.Size(m)
}
func (m *AgentMask) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentMask.DiscardUnknown(m)
}

var xxx_messageInfo_AgentMask proto.InternalMessageInfo

func (m *AgentMask) GetId() bool {
	if m != nil {
		return m.Id
	}
	return false
}

func (m *AgentMask) GetAttestationType() bool {
	if m != nil {
		return m.AttestationType
	}
	return false
}

func (m *AgentMask) GetX509SvidSerialNumber() bool {
	if m != nil {
		return m.X509SvidSerialNumber
	}
	return false
}

func (m *AgentMask) GetX509SvidExpiresAt() bool {
	if m != nil {
		return m.X509SvidExpiresAt
	}
	return false
}

func (m *AgentMask) GetSelectors() bool {
	if m != nil {
		return m.Selectors
	}
	return false
}

func (m *AgentMask) GetBanned() bool {
	if m != nil {
		return m.Banned
	}
	return false
}

func init() {
	proto.RegisterType((*Agent)(nil), "spire.types.Agent")
	proto.RegisterType((*AgentMask)(nil), "spire.types.AgentMask")
}

func init() { proto.RegisterFile("agent.proto", fileDescriptor_56ede974c0020f77) }

var fileDescriptor_56ede974c0020f77 = []byte{
	// 302 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xcf, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0xc9, 0xe6, 0x46, 0x97, 0x81, 0x3f, 0xa2, 0x8e, 0x20, 0x82, 0x65, 0xa7, 0x7a, 0x30,
	0x19, 0x4e, 0x0f, 0x1e, 0x27, 0x78, 0xd4, 0x43, 0xe7, 0xc9, 0x4b, 0x49, 0xd7, 0xb7, 0x19, 0xdc,
	0xd2, 0xd2, 0xbc, 0x49, 0xf7, 0xef, 0xfa, 0x3f, 0x78, 0x97, 0x66, 0xab, 0x56, 0x11, 0x65, 0xc7,
	0xf7, 0x3e, 0xdf, 0x2f, 0xbc, 0x4f, 0x1b, 0xda, 0x55, 0x33, 0x30, 0x28, 0xb2, 0x3c, 0xc5, 0x94,
	0x75, 0x6d, 0xa6, 0x73, 0x10, 0xb8, 0xca, 0xc0, 0x9e, 0x9c, 0xb9, 0xe1, 0xc2, 0x40, 0x81, 0xd2,
	0x6d, 0xa4, 0x85, 0x39, 0x4c, 0x30, 0xcd, 0xd7, 0xe9, 0xfe, 0x3b, 0xa1, 0xad, 0x51, 0xd9, 0x66,
	0xbb, 0xb4, 0xa1, 0x13, 0x4e, 0x7c, 0x12, 0x74, 0xc2, 0x86, 0x4e, 0xd8, 0x39, 0xdd, 0x57, 0x88,
	0x60, 0x51, 0xa1, 0x4e, 0x4d, 0x54, 0xb6, 0x79, 0xc3, 0xd1, 0xbd, 0xda, 0xfe, 0x71, 0x95, 0x01,
	0xbb, 0xa2, 0xbd, 0xe2, 0x7a, 0x70, 0x63, 0x5f, 0x75, 0x12, 0x59, 0xc8, 0xb5, 0x9a, 0x47, 0x66,
	0xb9, 0x88, 0x21, 0xe7, 0x4d, 0x57, 0x38, 0xaa, 0xe8, 0xd8, 0xc1, 0x07, 0xc7, 0x98, 0xa0, 0x87,
	0x9f, 0x2d, 0x28, 0xca, 0x3b, 0x6d, 0xa4, 0x90, 0xef, 0xf8, 0x24, 0x68, 0x86, 0x07, 0x15, 0xba,
	0x5b, 0x93, 0x11, 0xb2, 0x21, 0xed, 0x54, 0xc7, 0x5b, 0xde, 0xf2, 0x9b, 0x41, 0xf7, 0xf2, 0x58,
	0xd4, 0x64, 0xc5, 0x78, 0x43, 0xc3, 0xaf, 0x1c, 0xeb, 0xd1, 0x76, 0xac, 0x8c, 0x81, 0x84, 0xb7,
	0x7d, 0x12, 0x78, 0xe1, 0x66, 0xea, 0xbf, 0x11, 0xda, 0x71, 0xde, 0xf7, 0xca, 0xbe, 0xd4, 0xdc,
	0xbd, 0x3f, 0xdd, 0xbd, 0x6d, 0xdd, 0xbd, 0xed, 0xdd, 0xbd, 0xdf, 0xdc, 0x4f, 0xbf, 0xbb, 0x97,
	0xa9, 0xff, 0x25, 0x6f, 0x07, 0x4f, 0x62, 0xa6, 0xf1, 0x79, 0x19, 0x8b, 0x49, 0xba, 0x90, 0x36,
	0xd3, 0xd3, 0x29, 0x48, 0xf7, 0xc5, 0xa4, 0xfb, 0xfb, 0xf2, 0xe7, 0xeb, 0x88, 0xdb, 0x6e, 0x3f,
	0xfc, 0x08, 0x00, 0x00, 0xff, 0xff, 0xb4, 0x25, 0x89, 0xc1, 0x52, 0x02, 0x00, 0x00,
}
